version: '3.8'
services:
  frontend:
    image: antoniopapa1991/admin-frontend
    depends_on:
      - backend
    # networks:
    #   - app

  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABSE: admin
      DB_USERNAME: admin1
      DB_PASSWORD: admin1
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis-server
    # networks:
    #   - app

  db:
    container_name: admin_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin1
      MYSQL_PASSWORD: admin1
      MYSQL_ROOT_PASSWORD: admin1
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    # networks:
    #   - app

  redis-server:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 9001:80

# networks:
#   app:

